import express from "express";
import bodyParser from "body-parser";
import axios from "axios";

const port = 3000;
const app = express();
const countryJSON =
  `{
  "afghanistan": "AF",
  "alandislands": "AX",
  "albania": "AL",
  "algeria": "DZ",
  "americansamoa": "AS",
  "andorra": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antiguaandbarbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "aruba": "AW",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "bhutan": "BT",
  "bolivia": "BO",
  "bosniaandherzegovina": "BA",
  "botswana": "BW",
  "bouvetisland": "BV",
  "brazil": "BR",
  "britishindianoceanterritory": "IO",
  "bruneidarussalam": "BN",
  "bulgaria": "BG",
  "burkinafaso": "BF",
  "burundi": "BI",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "capeverde": "CV",
  "caymanislands": "KY",
  "centralafricanrepublic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "christmasisland": "CX",
  "cocos(keeling)islands": "CC",
  "colombia": "CO",
  "comoros": "KM",
  "congo": "CG",
  "congo,democraticrepublic": "CD",
  "cookislands": "CK",
  "costarica": "CR",
  "coted'ivoire": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czechrepublic": "CZ",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominicanrepublic": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "elsalvador": "SV",
  "equatorialguinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "ethiopia": "ET",
  "falklandislands(malvinas)": "FK",
  "faroeislands": "FO",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "frenchguiana": "GF",
  "frenchpolynesia": "PF",
  "frenchsouthernterritories": "TF",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guernsey": "GG",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "heardisland&mcdonaldislands": "HM",
  "holysee(vaticancitystate)": "VA",
  "honduras": "HN",
  "hongkong": "HK",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran,islamicrepublicof": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "isleofman": "IM",
  "israel": "IL",
  "italy": "IT",
  "jamaica": "JM",
  "japan": "JP",
  "jersey": "JE",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "korea": "KR",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laopeople'sdemocraticrepublic": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libyanarabjamahiriya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macao": "MO",
  "macedonia": "MK",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshallislands": "MH",
  "martinique": "MQ",
  "mauritania": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mexico": "MX",
  "micronesia,federatedstatesof": "FM",
  "moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "netherlandsantilles": "AN",
  "newcaledonia": "NC",
  "newzealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norfolkisland": "NF",
  "northernmarianaislands": "MP",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestinianterritory,occupied": "PS",
  "panama": "PA",
  "papuanewguinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "pitcairn": "PN",
  "poland": "PL",
  "portugal": "PT",
  "puertorico": "PR",
  "qatar": "QA",
  "reunion": "RE",
  "romania": "RO",
  "russianfederation": "RU",
  "rwanda": "RW",
  "saintbarthelemy": "BL",
  "sainthelen": "SH",
  "saintkittsandnevis": "KN",
  "saintlucia": "LC",
  "saintmartin": "MF",
  "saintpierreandmiquelon": "PM",
  "saintvincentandgrenadines": "VC",
  "samoa": "WS",
  "sanmarino": "SM",
  "saotomeandprincipe": "ST",
  "saudiarabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierraleone": "SL",
  "singapore": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomonislands": "SB",
  "somalia": "SO",
  "southafrica": "ZA",
  "southgeorgiaandsandwichisl.": "GS",
  "spain": "ES",
  "srilanka": "LK",
  "sudan": "SD",
  "suriname": "SR",
  "svalbardandjanmayen": "SJ",
  "swaziland": "SZ",
  "sweden": "SE",
  "switzerland": "CH",
  "syrianarabrepublic": "SY",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tokelau": "TK",
  "tonga": "TO",
  "trinidadandtobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "turkmenistan": "TM",
  "turksandcaicosislands": "TC",
  "tuvalu": "TV",
  "uganda": "UG",
  "ukraine": "UA",
  "unitedarabemirates": "AE",
  "unitedkingdom": "GB",
  "unitedstates": "US",
  "unitedstatesoutlyingislands": "UM",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "venezuela": "VE",
  "vietnam": "VN",
  "virginislands,british": "VG",
  "virginislands,u.s.": "VI",
  "wallisandfutuna": "WF",
  "westernsahara": "EH",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
  "northmacedonia": "MK",
  "češka": "CZ"
}`;

import dotenv from "dotenv";
dotenv.config();
const yourAPIKey = process.env.yourAPIKey;

const countryCodes = JSON.parse(countryJSON);

app.use(express.static("public"));
app.use(bodyParser.urlencoded({ extended: true }));

app.set("view engine", "ejs");

app.get("/", (req, res) => {
  res.render("index.ejs", { content: "API Response." });
});

app.post("/", async (req, res) => {
  const country = req.body.country.toLowerCase().replace(/\s+/g, "");
  const city = req.body.city;
  const state = req.body.state;
  const countryCode = countryCodes[country];

  try {
    let URL;
    URL = `https://api.openweathermap.org/data/2.5/weather?q=${city},${countryCode}&appid=${yourAPIKey}&units=metric`;

    
    const response = await axios.get(URL);
    res.render("index.ejs", { 
      content: response.data,
    });
    console.log(response.data);
  } catch (error) {
    
  }
});

app.listen(port, () => {
  console.log(`Listening to Port ${port}`);
});

